# Generated by Django 5.1.4 on 2024-12-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Put product name', max_length=150, verbose_name='Product name')),
                ('product_model', models.CharField(help_text='Put product model', max_length=150, verbose_name='Product model')),
                ('product_launched_at', models.DateField(help_text='In format 2024-08-04', verbose_name="Product's launch date")),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text="Put member's name", max_length=150, verbose_name="Member's name")),
                ('member_email', models.EmailField(help_text="Put member's contact email", max_length=254, unique=True, verbose_name="Member's contact email")),
                ('member_country', models.CharField(help_text="Put member's country", max_length=150, verbose_name="Member's country")),
                ('member_city', models.CharField(blank=True, help_text="Put member's city", max_length=150, null=True, verbose_name="Member's city")),
                ('member_street', models.CharField(blank=True, help_text="Put member's street", max_length=150, null=True, verbose_name="Member's street")),
                ('member_building_no', models.SmallIntegerField(blank=True, help_text="Put member's building_no", null=True, verbose_name="Member's building_no")),
                ('member_debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Member's debt to supplier")),
                ('member_created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date&Time of Member's creation")),
                ('member_type', models.CharField(choices=[('pl', 'plant'), ('rn', 'retail_net'), ('rp', 'retail_private')], default='pl', help_text="Put member's type", max_length=2, verbose_name="Member's' type")),
                ('supplier_for_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('product', models.ForeignKey(help_text='Choose Product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='member.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Chain member',
                'verbose_name_plural': 'Chain members',
                'ordering': ['member_name'],
            },
        ),
    ]
