# Generated by Django 5.1.4 on 2024-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_level',
            field=models.SmallIntegerField(blank=True, help_text='Choose hierarchy level in the trade net', null=True, verbose_name='Hierarchy level'),
        ),
    ]
