# Generated by Django 5.1.4 on 2024-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_member_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Hierarchy level'),
        ),
    ]
